module.exports = {
  content: [
    './**/*.php',
    './**/*.html',
    '!./vendor/**',
    '!./node_modules/**',
    '!./tmp/**',
    '!./assets/js/bootstrap.min.js',
    '!./assets/js/bootstrap.min.js.map'
  ],
  css: ['./tmp/bootstrap.css'],
  safelist: [
    'show',
    'fade',
    'collapsing',
    'collapse',
    'modal-open',
    'modal-backdrop',
    'active',
    'disabled',
    'showing',
    /^modal/,
    /^carousel/,
    /^col-/,
    /^row$/,
    /^container/,
    /^d-/, 
    /^flex-/, 
    /^justify-content-/, 
    /^align-/, 
    /^text-/, 
    /^m[trblxy]?-/,
    /^p[trblxy]?-/,
    /^w-/, 
    /^h-/, 
    /^img-/, 
    /^btn-/, 
    /^input-group/, 
    /^form-control/, 
    /^alert/, 
    /^table/, 
    /^nav/,
    /^card/
  ],
  keyframes: true,
  variables: true
};
