<!-- ***** Inicio Seccion de Clientes (EN) ***** -->
<section class="section padding-top-70 padding-bottom-0" id="Clientes-en" aria-labelledby="title-why-kasu-nft">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 col-md-12 col-sm-12 align-self-center" data-scroll-reveal="enter left move 30px over 0.6s after 0.4s">
        <div class="center-heading">
          <h2 id="title-why-kasu-nft" class="section-title">Why KASU NFT?</h2>
        </div>

        <div class="center-heading">
          <p>
            KASU was founded in 2016 as a project which seeks to provide an accessible option to Mexican families that need life insurance at a good price. When you buy KASU, as our customer, you don’t have to worry about paying annual renewals, deductibles, or hidden charges; this means that with a single payment you will be protected for your whole life. We innovate by offering you a product according to the needs of the Latin insurance market.
          </p>
          <br>
          <p>
            We have decided to wrap up the basic information of each of our clients and coin it in a series of NFTs that will allow, with the initial sale and royalties, to grow the assets of the investment fund and to share the profits between the client and the NFT’s owner.
          </p>
          <br>
        </div>
      </div>

      <div class="col-lg-1"></div>

      <div class="col-lg-6 col-md-12 col-sm-12 align-self-center mobile-top-fix">
        <a href="https://opensea.io/collection/kasunft" target="_blank" rel="noopener noreferrer" aria-label="Open KASU NFT collection on OpenSea">
          <img
            id="NftKAsu"
            src="/assets/images/nft2.gif"
            class="rounded img-fluid d-block mx-auto"
            alt="KASU NFT animated preview"
            style="width:85%;"
            loading="lazy"
            decoding="async"
            width="960"
            height="960">
        </a>
      </div>
    </div>
    <br><br>
  </div>
</section>

<!-- ***** Advantages ***** -->
<section class="mini1" id="Advantages-en" aria-labelledby="title-advantages-en">
  <div class="mini-content">
    <div class="container">
      <div class="col-lg-12">
        <div class="center-heading">
          <h2 id="title-advantages-en" class="section-title"><strong>KASU NFT</strong> IS MORE THAN CRYPTO ART, IT’S ABOUT PEOPLE</h2>
        </div>
      </div>

      <div class="center-heading">
        <p>
          Through this collection we expect to make KASU's investment staking fund: with the raised capital we will create a cryptocurrency staking that allows NFTs to get 60% of the staking’s production, shared in the proportion stated in each NFT’s metadata. The remaining profit will be reinvested in the investment fund, allowing it to provide greater services for KASU clients and keep generating distributable profits for the NFTs, creating a symbiosis between the NFTs and our clients.
        </p>
        <br>
        <p>
          Thus, during the NFT’s lifetime, you will receive profit generated by the staking and the investment fund. Clients will receive additional generated services as well. When the service is delivered to the clients, you will receive 50% of the remaining investment fund and your NFT will be deactivated—leaving you an incredible experience and a unique collectible.
        </p>
        <br>
        <p>
          Every NFT birthday, the ETH address that owns the NFT will receive 30% of the profit produced by the investment fund, distributed in the proportion stated in each NFT’s metadata. So feel free to pick, from our collection, the date you like the most—or trade your NFT to capture sale gains.
        </p>
        <br>

        <div class="row d-flex justify-content-center">
          <table class="table table-bordered table-striped w-auto" aria-describedby="rewards-table-desc">
            <caption id="rewards-table-desc" class="sr-only">Summary of stock, daily rewards and starting price by NFT age range</caption>
            <thead>
              <tr>
                <th scope="col">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Years NFT&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th scope="col">&nbsp;&nbsp;Stock*&nbsp;&nbsp;</th>
                <th scope="col">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Daily Reward**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th scope="col">&nbsp;&nbsp;Starting Price&nbsp;&nbsp;</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">02–29</th>
                <td>131</td>
                <td>0.000245 ETH</td>
                <td>0.16 ETH</td>
              </tr>
              <tr>
                <th scope="row">30–49</th>
                <td>162</td>
                <td>0.000417 ETH</td>
                <td>0.28 ETH</td>
              </tr>
              <tr>
                <th scope="row">50–54</th>
                <td>46</td>
                <td>0.000712 ETH</td>
                <td>0.47 ETH</td>
              </tr>
              <tr>
                <th scope="row">55–59</th>
                <td>46</td>
                <td>0.000982 ETH</td>
                <td>0.65 ETH</td>
              </tr>
              <tr>
                <th scope="row">60–64</th>
                <td>30</td>
                <td>0.001424 ETH</td>
                <td>0.95 ETH</td>
              </tr>
              <tr>
                <th scope="row">65–69</th>
                <td>13</td>
                <td>0.001939 ETH</td>
                <td>1.00 ETH</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div>
          <ul>
            <li>* Number of NFTs minted per 2021 series</li>
            <li>** Minimum expected daily reward directed to the NFT</li>
          </ul>
        </div>
        <br>
      </div>
      <br>
    </div>
  </div>
</section>

<!-- ***** Products ***** -->
<section class="section colored" id="Buy-en" aria-labelledby="title-rewards-policy-en">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-12 col-sm-12 align-self-center mobile-top-fix">
        <br>
        <a href="https://opensea.io/collection/kasunft" target="_blank" rel="noopener noreferrer" aria-label="Go to OpenSea to buy KASU NFTs">
          <img
            id="fideicomiso"
            src="/assets/images/funcionamiento.png"
            class="rounded img-fluid d-block mx-auto"
            alt="KASU NFT collection buying guide"
            style="width:85%;"
            loading="lazy"
            decoding="async"
            width="1200"
            height="900">
        </a>
      </div>

      <div class="col-lg-1"></div>

      <div class="col-lg-5 col-md-12 col-sm-12 align-self-lef" data-scroll-reveal="enter left move 30px over 0.6s after 0.4s">
        <br><br>
        <div class="center-heading">
          <h2 id="title-rewards-policy-en" class="section-title">REWARDS POLICY</h2>
        </div>

        <div class="left-heading">
          <p>Investments are carried out through stock-market instruments and cryptocurrency mining.</p>
          <br>
          <p>Staking produces a daily revenue assigned to the NFT owner in the percentages stated in the NFT metadata.</p>
          <br>
          <p>Investments in stock-market instruments distribute rewards to the NFT owner’s address on every NFT birthday.</p>
        </div>
      </div>
    </div>
    <br><br>
  </div>
</section>

<!-- ***** Collections ***** -->
<section class="section" id="Collections-en" style="display:none" aria-labelledby="title-collections-en">
  <div class="container">
    <br><br>
    <div class="row">
      <div class="offset-lg-3 col-lg-6">
        <div class="center-heading">
          <h3 id="title-collections-en">Meet the Collections of <strong>KASU NFT</strong></h3>
          <br>
        </div>
      </div>
    </div>

    <div class="row">
      <!-- Collection 2021 -->
      <div class="col-lg-4 col-md-6 col-sm-12">
        <a href="https://opensea.io/collection/kasunft" target="_blank" rel="noopener noreferrer" aria-label="Open KASU NFT 2021 collection on OpenSea">
          <div class="team-item">
            <div class="team-content">
              <i>
                <img src="/assets/images/nft2.gif" alt="KASU NFT collection 2021" style="width:35%;" loading="lazy" decoding="async" width="512" height="512">
              </i>
              <br>
              <h3>Collection 2021</h3>
              <p>KASU customers, who have registered since 2017, will be coined in this first NFT collection.</p>
              <p><strong>428 Items</strong></p>
            </div>
          </div>
        </a>
      </div>

      <!-- Collection 2022 -->
      <div class="col-lg-4 col-md-6 col-sm-12">
        <a href="https://opensea.io/collection/kasunft" target="_blank" rel="noopener noreferrer" aria-label="Open KASU NFT 2022 collection on OpenSea">
          <div class="team-item">
            <div class="team-content">
              <i>
                <img src="/assets/images/nft2.gif" alt="KASU NFT collection 2022" style="width:35%;" loading="lazy" decoding="async" width="512" height="512">
              </i>
              <br>
              <h3>Collection 2022</h3>
              <p>KASU customers, who have registered in 2022, will be coined in this first NFT collection.</p>
              <p><strong>120 Items</strong></p>
            </div>
          </div>
        </a>
      </div>

      <!-- Collection 2023 -->
      <div class="col-lg-4 col-md-6 col-sm-12">
        <a href="https://opensea.io/collection/kasunft" target="_blank" rel="noopener noreferrer" aria-label="Open KASU NFT 2023 collection on OpenSea">
          <div class="team-item">
            <div class="team-content">
              <i>
                <img src="/assets/images/nft2.gif" alt="KASU NFT collection 2023" style="width:35%;" loading="lazy" decoding="async" width="512" height="512">
              </i>
              <br>
              <h3>Collection 2023</h3>
              <p>KASU customers, who have registered in 2023, will be coined in this first NFT collection.</p>
              <p><strong>xxx Items</strong></p>
            </div>
          </div>
        </a>
      </div>
    </div>
    <br>
  </div>
</section>