<!-- ***** Inicio Seccion de Clientes ***** -->
<section class="section padding-top-70 padding-bottom-0" id="Clientes">
    <div class="container">
      <div class="row">
          <div class="col-lg-5 col-md-12 col-sm-12 align-self-center" data-scroll-reveal="enter left move 30px over 0.6s after 0.4s">
            <!-- <div class="col-lg-12"> -->
                <div class="center-heading">
                    <h2 class="section-title">Why KASU NFT?</h2>
                </div>
            <!-- </div> -->
            <!-- <div class="offset-lg-3 col-lg-6"> -->
                <div class="center-heading">
                    <p>
                      KASU was founded in 2016 as a project which seeks to provide an accessible option to Mexican families that need life insurance at a good price. When you buy KASU, as our customer, you don’t have to worry about paying annual renewals, deductibles, or hidden charges, this means that with a single payment you will be protected for your whole life. We innovate by offering you a product according to the needs of the latin insurance market.
                    </p>
                    <br>
                    <p>
                      We have decided to wrap up the basic information of each of our clients and coin it in a series of NFTs that will allow, with the initial sale and royalties, to make grow the assets of the investment fund, and to share the profits between the client and the NFT’s owner.
                    </p>
                  <br>
              <!-- </div> -->
            </div>
          </div>
          <div class="col-lg-1"></div>
          <div class="col-lg-6 col-md-12 col-sm-12 align-self-center mobile-top-fix">
            <a href="https://opensea.io/collection/kasunft" target="_blank" rel="noopener noreferrer">
              <img id="NftKAsu" src="/assets/images/nft2.gif" class="rounded img-fluid d-block mx-auto" alt="Guia para compra" style="width:85%;">
            </a>
          </div>
      </div>
      <br>
      <br>
    </div>
</section>
<!-- ***** Porque contratar Ventajas***** -->
<section class="mini1" id="Ventajas">
    <div class="mini-content">
        <div class="container">
              <div class="col-lg-12">
                  <div class="center-heading">
                      <h2 class="section-title"><strong>KASU NFT</strong> IS MORE THAN CRYPTO ART, IT’S ABOUT PEOPLE</h2>
                  </div>
              </div>
              <div class="center-heading">
                  <p>
                    Through this collection we expect to make KASU's investment Staking  fund, with the raised capital we will create a cryptocurrency Staking that allows NFTs to get 60% of the Staking's production, which is meant to be shared in the proportion of each NFT’s metadata. The remaining profit will be reinvented in the investment fund: allowing it to provide greater and better services for KASU clients, keeping on generating distributable profits for the NFTs and creating a symbiosis between the NFTs and the funds from our clients.
                  </p>
                  <br>
                  <p>
                    Thus, during the NFT’s lifetime, you will receive additional profit generated by the Staking  itself and the investment fund. Clients will receive additional generated services as well. By the time the service is delivered to the clients, you will be getting 50% from the remaining investment fund, being your NFT deactivated and letting you keep an incredible experience and a unique collection.
                  </p>
                  <br>
                  <p>
                    Every single NFT's birthday, the ETH administration, which owns the NFT, will receive 30% of the profit produced by the Investment fund to be distributed in the proportion of each NFT’s metadata. So feel free to either search and pick, from our collection, the date you like the most, or just sell your NFT to earn a cost utility.
                  </p>
                  <br>
                  <div  class="row d-flex justify-content-center">
                    <table border="1">
                      <tr>
                         <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Years NFT&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                         <th>&nbsp;&nbsp;Stock*&nbsp;&nbsp;</th>
                         <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Daily Reward**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                         <th>&nbsp;&nbsp;starting price&nbsp;&nbsp;</th>
                      </tr>
                      <tr>
                         <th>02 a 29</th>
                         <td>131</td>
                         <td>0,000245 ETH</td>
                         <td>0.16 ETH</td>
                      </tr>
                      <tr>
                         <th>30 a 49</th>
                         <td>162</td>
                         <td>0,000417 ETH</td>
                         <td>0.28 ETH</td>
                      </tr>
                      <tr>
                         <th>50 a 54</th>
                         <td>46</td>
                         <td>0,000712 ETH</td>
                         <td>0.47 ETH</td>
                      </tr>
                      <tr>
                         <th>55 a 59</th>
                         <td>46</td>
                         <td>0,000982 ETH</td>
                         <td>0.65 ETH</td>
                      </tr>
                      <tr>
                         <th>60 a 64</th>
                         <td>30</td>
                         <td>0,001424 ETH</td>
                         <td>0.95 ETH</td>
                      </tr>
                      <tr>
                         <th>65 a 69</th>
                         <td>13</td>
                         <td>0,001939 ETH</td>
                         <td>1.00 ETH</td>
                      </tr>
                    </table>
                  </div>
                  <div>
                    <ul>
                        <li>*Number of NFTs minted per series 2021</li>
                        <li>**Minimum expected daily reward at NFT</li>
                    </ul>
                  </div>
                  <br>
            </div>
            <br>
        </div>
    </div>
</section>
<!--***** Contact Us Start ***** -->
<!-- ***** Productos ***** -->
<section class="section colored" id="Comprar">
  <div class="container">
    <div class="row">
        <div class="col-lg-6 col-md-12 col-sm-12 align-self-center mobile-top-fix">
          <br>
          <a href="https://opensea.io/collection/kasunft" target="_blank" rel="noopener noreferrer">
            <img id="fideicomiso" src="/assets/images/funcionamiento.png" class="rounded img-fluid d-block mx-auto" alt="Guia para compra" style="width:85%;">
          </a>
        </div>
        <div class="col-lg-1"></div>
        <div class="col-lg-5 col-md-12 col-sm-12 align-self-lef" data-scroll-reveal="enter left move 30px over 0.6s after 0.4s">
          <!-- <div class="col-lg-12"> -->
              <br><br>
              <div class="center-heading">
                  <h2 class="section-title"> REWARDS POLICY </h2>
              </div>
          <!-- </div> -->
          <!-- <div class="offset-lg-3 col-lg-6"> -->
              <div class="left-heading">
                <p>
                  Investments are carried out through stock-market instruments and cryptocurrency mining.
                </p>
                <br>
                <p>
                  Staking produce a daily revenue that is addressed to the NFT’s owner in the percentages that are stated in the NFT’s metadata.
                </p>
                <br>
                <p>
                  Investments in stock-market instruments distribute the rewards to the address of the NFT’s owner every NFT’s birthday date.
                </p>
            <!-- </div> -->
          </div>
        </div>
    </div>
    <br>
    <br>
  </div>
</section>
<!-- ***** Opiniones de los clientes ***** -->
<section class="section" id="testimonials" display="none">
    <div class="container" >
      <br><br>
      <div class="row">
          <div class="offset-lg-3 col-lg-6">
              <div class="center-heading">
                  <p>Meet the Collections of <strong>KASU NFT</strong> </p>
                  <br>
              </div>
          </div>
      </div>
      <!-- ***** Section Title End ***** -->
      <div class="row">
          <!-- ***** Testimonials Item Start ***** -->
          <div class='col-lg-4 col-md-6 col-sm-12'>
              <a href="https://opensea.io/collection/kasunft" target="_blank" rel="noopener noreferrer">
              <div class='team-item'>
                  <div class='team-content'>
                      <i><img src='/assets/images/nft2.gif' alt='Testimonio' style="width:35%;"></i>
                      <br>
                      <h3>Collection 2021</h3>
                      <p>KASU customers, who have registered since 2017, will be coined in this first NFT collection.</p>
                      <p><strong>428 Items</strong></p>
                  </div>
              </div>
              </a>
          </div>
          <div class='col-lg-4 col-md-6 col-sm-12'>
              <a href="https://opensea.io/collection/kasunft" target="_blank" rel="noopener noreferrer">
              <div class='team-item'>
                  <div class='team-content'>
                      <i><img src='/assets/images/nft2.gif' alt='Testimonio' style="width:35%;"></i>
                      <br>
                      <h3>Collection 2022</h3>
                      <p>KASU customers, who have registered in 2022, will be coined in this first NFT collection.</p>
                      <p><strong>120 Items</strong></p>
                  </div>
              </div>
              </a>
          </div>
          <div class='col-lg-4 col-md-6 col-sm-12'>
              <a href="https://opensea.io/collection/kasunft" target="_blank" rel="noopener noreferrer">
              <div class='team-item'>
                  <div class='team-content'>
                      <i><img src='/assets/images/nft2.gif' alt='Testimonio' style="width:35%;"></i>
                      <br>
                      <h3>Collection 2023</h3>
                      <p>KASU customers, who have registered in 2023, will be coined in this first NFT collection.</p>
                      <p><strong>xxx Items</strong></p>
                  </div>
              </div>
              </a>
          </div>
          <!-- ***** Testimonials Item End ***** -->
        </div>
        <br>
    </div>
</section>
